apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: nahuetomas/blog-event-bus
          env:
            - name: POSTS_URL
              value: http://posts-clusterip-srv:4000
            - name: COMMENTS_URL
              value: http://comments-clusterip-srv:4001
            - name: QUERY_URL
              value: http://query-clusterip-srv:4002
            - name: MODERATION_URL
              value: http://moderation-clusterip-srv:4003
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-clusterip-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
